version: '3.2'
services:
  app:
    image: node
    container_name: 'node'
    ports:
      - '3020:3020'
    volumes:
      - ./app/:/home/app:rw
    command: npm run dev
    working_dir: /home/app
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: digitaldisplay
